server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://47.106.212.4:3306/yzjiang_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jap:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

logging:
  path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%-level]-[%t]-[%c{1.}.%M(%L)]: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%-level]-[%t]-[%c{1.}.%M(%L)]: %msg%n"